
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "GameWebServiceService", targetNamespace = "http://webServices.SoapHomeWork.example.com/", wsdlLocation = "http://0.0.0.0/8088/?wsdl")
public class GameWebServiceService
    extends Service
{

    private static final URL GAMEWEBSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException GAMEWEBSERVICESERVICE_EXCEPTION;
    private static final QName GAMEWEBSERVICESERVICE_QNAME = new QName("http://webServices.SoapHomeWork.example.com/", "GameWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://0.0.0.0/8088/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMEWEBSERVICESERVICE_WSDL_LOCATION = url;
        GAMEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public GameWebServiceService() {
        super(__getWsdlLocation(), GAMEWEBSERVICESERVICE_QNAME);
    }

    public GameWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMEWEBSERVICESERVICE_QNAME, features);
    }

    public GameWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, GAMEWEBSERVICESERVICE_QNAME);
    }

    public GameWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMEWEBSERVICESERVICE_QNAME, features);
    }

    public GameWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameWS
     */
    @WebEndpoint(name = "GameWSPort")
    public GameWS getGameWSPort() {
        return super.getPort(new QName("http://webServices.SoapHomeWork.example.com/", "GameWSPort"), GameWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameWS
     */
    @WebEndpoint(name = "GameWSPort")
    public GameWS getGameWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.SoapHomeWork.example.com/", "GameWSPort"), GameWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw GAMEWEBSERVICESERVICE_EXCEPTION;
        }
        return GAMEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
