
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "GameWS", targetNamespace = "http://webServices.SoapHomeWork.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameWS {


    /**
     * 
     * @param id
     * @return
     *     returns proxy.Game
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGameById", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.GetGameById")
    @ResponseWrapper(localName = "getGameByIdResponse", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.GetGameByIdResponse")
    @Action(input = "http://webServices.SoapHomeWork.example.com/GameWS/getGameByIdRequest", output = "http://webServices.SoapHomeWork.example.com/GameWS/getGameByIdResponse")
    public Game getGameById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deleteGameById", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.DeleteGameById")
    @ResponseWrapper(localName = "deleteGameByIdResponse", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.DeleteGameByIdResponse")
    @Action(input = "http://webServices.SoapHomeWork.example.com/GameWS/deleteGameByIdRequest", output = "http://webServices.SoapHomeWork.example.com/GameWS/deleteGameByIdResponse")
    public void deleteGameById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Game>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllGames", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.GetAllGames")
    @ResponseWrapper(localName = "getAllGamesResponse", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.GetAllGamesResponse")
    @Action(input = "http://webServices.SoapHomeWork.example.com/GameWS/getAllGamesRequest", output = "http://webServices.SoapHomeWork.example.com/GameWS/getAllGamesResponse")
    public List<Game> getAllGames();

    /**
     * 
     * @param game
     */
    @WebMethod
    @RequestWrapper(localName = "addGame", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.AddGame")
    @ResponseWrapper(localName = "addGameResponse", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.AddGameResponse")
    @Action(input = "http://webServices.SoapHomeWork.example.com/GameWS/addGameRequest", output = "http://webServices.SoapHomeWork.example.com/GameWS/addGameResponse")
    public void addGame(
        @WebParam(name = "game", targetNamespace = "")
        Game game);

    /**
     * 
     * @param game
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "updateGame", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.UpdateGame")
    @ResponseWrapper(localName = "updateGameResponse", targetNamespace = "http://webServices.SoapHomeWork.example.com/", className = "proxy.UpdateGameResponse")
    @Action(input = "http://webServices.SoapHomeWork.example.com/GameWS/updateGameRequest", output = "http://webServices.SoapHomeWork.example.com/GameWS/updateGameResponse")
    public void updateGame(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "game", targetNamespace = "")
        Game game);

}
